VARS="LineText
DestinationStop
TripStatus
ScheduledDISArrivalTime
ExpectedDISArrivalTime
ScheduledDISDepartureTime
ExpectedDISDepartureTime
StopPosition"


echo "/*
 * CODE BLOCK GENERATED BY SCRIPT scripts/realtime.sh
 */"

echo "@Override
public void startElement(String namespaceURI, String localName, 
              String qName, Attributes atts) throws SAXException {"


echo "    if (!inDISDeviation) {
        if (localName.equals(\"DISDeviation\")) {
            inDISDeviation = true;
            data = new RealtimeData();
        }"
for x in $VARS; do
echo "    } else if (localName.equals(\"$x\")) {
        in$x = true;"
done
echo "    }"
echo "}"

echo ""
echo ""

echo "@Override
public void endElement(String namespaceURI, String localName, String qName) {
    if (!inDISDeviation) return;
    if (localName.equals(\"DISDeviation\")) {
        /*
         * on StopMatch we're at the end, and we need to add the station to the station list.
         */
        inDISDeviation = false;
        realtimeList.add(data);"
    
for x in $VARS; do
echo "    } else if (localName.equals(\"$x\")) {
        in$x = false;"
done
echo "    }"
echo "}"


echo ""
echo ""

echo "@Override
public void characters(char ch[], int start, int length) { 
    if (!inDISDeviation) return;"

for x in $VARS; do
echo "    } else if (in$x) {
        // TODO"
done
echo "    }"
echo "}"

echo "/*
 * END CODE BLOCK GENERATED BY SCRIPT scripts/realtime.sh
 */"
