VARS="DepartureStopId
DepartureStopName
DepartureTime
ArrivalStopId
ArrivalStopName
ArrivalTime
Line
Destination
TransportationName
WaitingTime"


echo "/*
 * CODE BLOCK GENERATED BY SCRIPT scripts/route.sh
 */"

echo "private boolean inTravelStage = false;"
for x in $VARS; do
    echo private boolean in$x = false";"
done

echo "@Override
public void startElement(String namespaceURI, String localName, 
              String qName, Attributes atts) throws SAXException {"


echo "    if (!inTravelStage) {
        if (localName.equals(\"TravelStage\")) {
            inTravelStage = true;
            routeData = new RouteData();
        }"
for x in $VARS; do
echo "    } else if (localName.equals(\"$x\")) {
        in$x = true;"
done
echo "    }"
echo "}"

echo ""
echo ""

echo "@Override
public void endElement(String namespaceURI, String localName, String qName) {
    if (!inTravelStage) return;
    if (localName.equals(\"TravelStage\")) {
        /*
         * on StopMatch we're at the end, and we need to add the station to the station list.
         */
        inTravelStage = false;
        routeList.add(routeData);"
    
for x in $VARS; do
echo "    } else if (localName.equals(\"$x\")) {
        in$x = false;"
done
echo "    }"
echo "}"


echo ""
echo ""

echo "@Override
public void characters(char ch[], int start, int length) { 
    if (!inTravelStage) return;"

for x in $VARS; do
echo "    } else if (in$x) {
        // TODO"
done
echo "    }"
echo "}"

echo "/*
 * END CODE BLOCK GENERATED BY SCRIPT scripts/route.sh
 */"
