BLOCK="Place"
VARS="Zone
X
Y
ID
Name
District
Type"


echo "/*
 * CODE BLOCK GENERATED BY SCRIPT scripts/search.sh
 */"

echo "private boolean in${BLOCK} = false;"
for x in $VARS; do
    echo private boolean in$x = false";"
done

echo "@Override
public void startElement(String namespaceURI, String localName, 
              String qName, Attributes atts) throws SAXException {"


echo "    if (!in${BLOCK}) {
        if (localName.equals(\"${BLOCK}\")) {
            in${BLOCK} = true;
            routeData = new RouteData();
        }"
for x in $VARS; do
echo "    } else if (localName.equals(\"$x\")) {
        in$x = true;"
done
echo "    }"
echo "}"

echo ""
echo ""

echo "@Override
public void endElement(String namespaceURI, String localName, String qName) {
    if (!inTravelStage) return;
    if (localName.equals(\"${BLOCK}\")) {
        /*
         * on StopMatch we're at the end, and we need to add the station to the station list.
         */
        in${BLOCK} = false;
        routeList.add(routeData);"
    
for x in $VARS; do
echo "    } else if (localName.equals(\"$x\")) {
        in$x = false;"
done
echo "    }"
echo "}"


echo ""
echo ""

echo "@Override
public void characters(char ch[], int start, int length) { 
    if (!in${BLOCK}) return;"

for x in $VARS; do
echo "    } else if (in$x) {
        // TODO"
done
echo "    }"
echo "}"

echo "/*
 * END CODE BLOCK GENERATED BY SCRIPT scripts/route.sh
 */"
